version: "3"
services:
    shinobi:
        image: shinobisystems/shinobi:latest
        container_name: shinobi_app
        env_file: .envShinobi
        depends_on:
           - db
        volumes:
           - ./Shinobi/config:/config
           - ./Shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
           - ./Shinobi/database:/var/lib/mysql
           - ./Shinobi/videos:/root/Shinobi/videos
           - ./Shinobi/videos2:/root/Shinobi/videos2
           - ./Shinobi/plugins:/root/Shinobi/plugins
           - ./dev/shm/Shinobi/streams:/dev/shm/streams
           - /etc/localtime:/etc/localtime:ro
        ports:
           - 8080:8080
        restart: always
        networks:
           - shinobi
#           - nginx-proxymanager

#    nginx:
#        image: nginx
#        container_name: shinobi_web
#        restart: always
#        volumes:
#           - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
#           - ./nginx.conf:/etc/nginx/nginx.conf
#           - ./nginx/logs:/var/log/nginx/
#           - ./nginx/config/conf.d:/etc/nginx/conf.d
        #ports:
        #  - 80:80
        #  - 443:443
#        networks:
#           - shinobi
#           - nginx-proxymanager

    db:
      image: mysql:5.7.26
      restart: always
      volumes:
        - ./mysql:/var/lib/mysql
       # - ./dbDump/:/docker-entrypoint-initdb.d
      env_file: .envMysql
      networks:
        - shinobi
#        - nginx-proxymanager

networks:
  nginx-proxymanager:
    external: true
  shinobi:
    external: true

